[package]
name = "twilight-sword"
version = "0.1.0"
edition = "2021"

[dependencies]
knus = "3.2.0"
miette = { version = "5.10.0", features = ["fancy"] }

[dependencies.tokio]
version = "1.42.0"
features = [
	"fs",
	"macros",
	"rt-multi-thread"
]